services:
  # WebDAV Server (custom nginx with WebDAV modules)
  webdav-server:
    build:
      context: .
      dockerfile: Dockerfile.webdav
    container_name: webdav-server
    env_file: .env
    ports:
      - "${WEBDAV_PORT_HTTP}:80"
      - "${WEBDAV_PORT_HTTPS}:443"
      - "${WEBDAV_STATUS_PORT}:${WEBDAV_STATUS_PORT}"  # Status endpoint port
    volumes:
      - webdav-data:/webdav
      - ./config/nginx/conf.d/webdav.conf:/etc/nginx/conf.d/webdav.conf
      - ./config/nginx/conf.d/status.conf:/etc/nginx/conf.d/status.conf
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - WEBDAV_USERNAME=${WEBDAV_USER}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - WEBDAV_HOST=${WEBDAV_HOST:-localhost}
      - WEBDAV_PORT_HTTP=${WEBDAV_PORT_HTTP}
      - WEBDAV_PORT_HTTPS=${WEBDAV_PORT_HTTPS}
      - WEBDAV_STATUS_PORT=${WEBDAV_STATUS_PORT}
      - WEBDAV_PATH=${WEBDAV_PATH:-/webdav}
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-auto}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
      - CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE:-0}
    networks:
      - medavault-network
    restart: unless-stopped

  # Filestash - Web-based WebDAV Client
  filestash-client:
    image: machines/filestash:latest
    container_name: filestash-client
    env_file: .env
    ports:
      - "${FILESTASH_PORT}:8334"
    volumes:
      - filestash-data:/app/data/state
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
      - FILESTASH_HOST=${FILESTASH_HOST:-localhost}
      - FILESTASH_PORT=${FILESTASH_PORT}
      - APPLICATION_URL=http://${FILESTASH_HOST:-localhost}:${FILESTASH_PORT}
      - WEBDAV_HOST=${WEBDAV_HOST:-localhost}
      - WEBDAV_PORT_HTTP=${WEBDAV_PORT_HTTP}
      - WEBDAV_USER=${WEBDAV_USER}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - WEBDAV_PATH=${WEBDAV_PATH:-/webdav}
      - FILESTASH_CONFIG=/app/data/state/filestash.conf
      - APP_LISTEN=0.0.0.0:8334
    depends_on:
      - webdav-server
    networks:
      - medavault-network
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"

  # Apache Camel Integration Service
  camel-integration:
    build:
      context: ./camel-integration
      dockerfile: Dockerfile
    container_name: camel-integration
    env_file: .env
    volumes:
      - ./camel-integration:/app
      - ./storage:/app/storage
      - ./processed:/app/processed
      - ./logs:/app/logs
      - ./config/application.properties:/app/config/application.properties
    environment:
      - TZ=${TZ:-UTC}
      - JAVA_OPTS=-Dwebdav.url=http://${WEBDAV_HOST:-webdav-server}:${WEBDAV_PORT_HTTP}${WEBDAV_PATH:-/webdav}
      - WEBDAV_USER=${WEBDAV_USER}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - WEBDAV_HOST=${WEBDAV_HOST:-webdav-server}
      - WEBDAV_PORT_HTTP=${WEBDAV_PORT_HTTP}
      - WEBDAV_PATH=${WEBDAV_PATH:-/webdav}
      - BACKEND_HOST=${BACKEND_HOST:-medavault-backend}
      - BACKEND_PORT=${BACKEND_PORT}
      - API_BASE_PATH=${API_BASE_PATH:-/api}
      - MEDAVAULT_API_URL=http://${BACKEND_HOST:-medavault-backend}:${BACKEND_PORT}${API_BASE_PATH:-/api}
      - POLL_INTERVAL=${POLL_INTERVAL:-10000}
      - PROCESSING_ENABLED=${PROCESSING_ENABLED:-true}
      - STORAGE_PATH=${STORAGE_PATH:-/app/storage}
      - PROCESSED_PATH=${PROCESSED_PATH:-/app/processed}
      - LOG_PATH=${LOG_PATH:-/app/logs}
    depends_on:
      - webdav-server
      - medavault-backend
    networks:
      - medavault-network
    restart: unless-stopped

  # MedaVault Backend (PostgreSQL + API)
  medavault-db:
    image: postgres:14
    container_name: medavault-db
    env_file: .env
    environment:
      POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER=${POSTGRES_USER}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - medavault-data:/var/lib/postgresql/data
      - ./config/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"
    networks:
      - medavault-network
    restart: unless-stopped

  # MedaVault API
  medavault-backend:
    build:
      context: ./medavault-backend
      dockerfile: Dockerfile
    container_name: medavault-backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./medavault-backend:/app
      - backend-node-modules:/app/node_modules
      - ./storage:/app/storage
      - ./processed:/app/processed
      - ./logs:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${BACKEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST:-0.0.0.0}
      - BACKEND_PORT=${BACKEND_PORT}
      - API_BASE_PATH=${API_BASE_PATH:-/api}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret}
      - WEBDAV_URL=http://${WEBDAV_HOST:-webdav-server}:${WEBDAV_PORT_HTTP}${WEBDAV_PATH:-/webdav}
      - WEBDAV_USER=${WEBDAV_USER}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - STORAGE_PATH=${STORAGE_PATH:-/app/storage}
      - PROCESSED_PATH=${PROCESSED_PATH:-/app/processed}
      - LOG_PATH=${LOG_PATH:-/app/logs}
    depends_on:
      - medavault-db
    networks:
      - medavault-network
    restart: unless-stopped

  # Web UI Dashboard
  web-dashboard:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile
    container_name: web-dashboard
    env_file: .env
    ports:
      - "${DASHBOARD_PORT}:80"
    volumes:
      - ./web-dashboard:/usr/share/nginx/html
      - ./config/dashboard-nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ:-UTC}
      - BACKEND_HOST=${BACKEND_HOST:-localhost}
      - BACKEND_PORT=${BACKEND_PORT}
      - API_BASE_PATH=${API_BASE_PATH:-/api}
      - WEBDAV_HOST=${WEBDAV_HOST:-localhost}
      - WEBDAV_PORT_HTTP=${WEBDAV_PORT_HTTP}
      - WEBDAV_PORT_HTTPS=${WEBDAV_PORT_HTTPS}
      - WEBDAV_STATUS_PORT=${WEBDAV_STATUS_PORT}
      - WEBDAV_PATH=${WEBDAV_PATH:-/webdav}
      - WEBDAV_USER=${WEBDAV_USER}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - FILESTASH_HOST=${FILESTASH_HOST:-localhost}
      - FILESTASH_PORT=${FILESTASH_PORT}
      - DASHBOARD_HOST=${DASHBOARD_HOST:-0.0.0.0}
      - DASHBOARD_PORT=${DASHBOARD_PORT}
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-auto}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
      - CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE:-0}
    networks:
      - medavault-network
    restart: unless-stopped

networks:
  medavault-network:
    driver: bridge

volumes:
  medavault-data:
  filestash-data:
  webdav-data:
